package com.shadentcg.shop.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents the billing document generated for a confirmed order (A2 class).
 *
 * <p>Responsibilities (from A2 CRC card):
 * <ul>
 *   <li>Hold billing details: invoice number, issue date, subtotal, GST, and total</li>
 *   <li>Be generated by {@link OrderProcessor} upon order confirmation</li>
 *   <li>Provide invoice data for display and email dispatch via {@link NotificationService}</li>
 * </ul>
 *
 * <p>A2 relationship: Order generates 1 Invoice (one-to-one).
 * Created by OrderProcessor as part of the checkout workflow.
 */
@Entity
@Table(name = "invoices")
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** A2: Invoice belongs to exactly one Order (1:1). */
    @OneToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "order_id", nullable = false, unique = true)
    private Order order;

    /** Human-readable invoice number, e.g. INV-2025-00042. */
    @Column(nullable = false, unique = true)
    private String invoiceNumber;

    @Column(nullable = false)
    private LocalDateTime issuedAt;

    /** Order subtotal before tax. */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal subtotal;

    /** GST amount (10% of subtotal for Australian orders). */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal gstAmount;

    /** Total including GST. */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    @Column(nullable = false)
    private String billingAddress;

    // ── Constructors ──────────────────────────────────────────────────

    public Invoice() {}

    /**
     * Creates an Invoice from the given order. Calculates GST (10%) automatically.
     *
     * @param order the confirmed order to invoice
     */
    public Invoice(Order order) {
        this.order          = order;
        this.invoiceNumber  = generateInvoiceNumber(order.getId());
        this.issuedAt       = LocalDateTime.now();
        this.billingAddress = order.getDeliveryAddress();
        this.subtotal       = order.getTotalAmount()
                                   .divide(BigDecimal.valueOf(1.10), 2, java.math.RoundingMode.HALF_UP);
        this.gstAmount      = order.getTotalAmount().subtract(this.subtotal);
        this.totalAmount    = order.getTotalAmount();
    }

    // ── Business logic ────────────────────────────────────────────────

    /**
     * Generates a human-readable invoice number from an order ID.
     *
     * @param orderId the order's DB ID
     * @return formatted string like "INV-2025-00042"
     */
    private String generateInvoiceNumber(Long orderId) {
        int year = LocalDateTime.now().getYear();
        return String.format("INV-%d-%05d", year, orderId);
    }

    // ── Getters & Setters ─────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Order getOrder() { return order; }
    public void setOrder(Order order) { this.order = order; }

    public String getInvoiceNumber() { return invoiceNumber; }
    public void setInvoiceNumber(String invoiceNumber) { this.invoiceNumber = invoiceNumber; }

    public LocalDateTime getIssuedAt() { return issuedAt; }
    public void setIssuedAt(LocalDateTime issuedAt) { this.issuedAt = issuedAt; }

    public BigDecimal getSubtotal() { return subtotal; }
    public void setSubtotal(BigDecimal subtotal) { this.subtotal = subtotal; }

    public BigDecimal getGstAmount() { return gstAmount; }
    public void setGstAmount(BigDecimal gstAmount) { this.gstAmount = gstAmount; }

    public BigDecimal getTotalAmount() { return totalAmount; }
    public void setTotalAmount(BigDecimal totalAmount) { this.totalAmount = totalAmount; }

    public String getBillingAddress() { return billingAddress; }
    public void setBillingAddress(String billingAddress) { this.billingAddress = billingAddress; }

    @Override
    public String toString() {
        return "Invoice{number='" + invoiceNumber + "', total=" + totalAmount + "}";
    }
}
